### ISSUE TITLE
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/ObfuscateText.19925c25.mjs') is not a valid name.

### ISSUE THREAD

**Issue by r3wt** [Contagious06/react-obfuscate-text#1]
Causes error when i tried to use it in my project, probably because it has to be transpiled?

**Comment by Contagious06** [comment]
Might have been due to this: https://github.com/developit/microbundle/pull/448, have updated :)

**Comment by r3wt** [comment]
@Contagious06 thank you for quick response, i will try and report back.
